# Generated by Django 4.2.5 on 2023-10-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('execution', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=255)),
                ('image_link', models.CharField(max_length=255)),
                ('tips', models.CharField(max_length=255)),
                ('destination_scale', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
