# Generated by Django 4.2.5 on 2023-10-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='destination_scale',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tips',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='volume',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
