# Generated by Django 4.2.5 on 2023-10-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_alter_exercise_destination_scale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_scale', models.CharField(max_length=255, null=True)),
                ('volume', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='destination_scale',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='volume',
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exercises', models.ManyToManyField(to='trainings.exerciseplan')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.exercise'),
        ),
    ]
