# Generated by Django 4.2.5 on 2023-10-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_exerciseweek_exerciseplan_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseweek',
            name='difficulty',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=255, null=True),
        ),
    ]
